userAuth/basicApp/urls.py
from django.urls import path
from basicApp import views

# SET THE NAMESPACE!
app_name = 'basicApp'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

userAuth/userAuth/urls.py
from django.contrib import admin
from django.urls import path, include
from basicApp import views

urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicApp/', include('basicApp.urls')),
    path('special/', views.special,name='special'),
    path('logout/', views.user_logout, name='logout'),
]

userAuth/basicApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional attributes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

userAuth/basicApp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicApp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

userAuth/basicApp/views.py
from django.shortcuts import render
from basicApp.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basicApp/index.html')

def register(request):
    registered = False
    if request.method == 'POST':
        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            # Save User Form to Database
            user = user_form.save()
            # Hash the password
            user.set_password(user.password)
            # Update with Hashed password
            user.save()

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)
            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            # Registration Successful!
            registered = True
        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)
    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basicApp/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):
    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid Login Details Supplied")
    else:
        return render(request, 'basicApp/login.html', {})

userAuth/basicApp/templates/basicApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class = 'navbar navbar-default navbar-fixed-top'>
      <div class="container">
        <ul class = 'nav navbar-nav'>
          <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basicApp:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
            <a class="nav-link" href="{% url 'basicApp:user_login' %}">Login</a>
          {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

userAuth/basicApp/templates/basicApp/index.html
{% extends "basicApp/base.html"%}
{% block body_block %}

<!-- This replaces jumbotron -->
<div class="bg-light p-5 rounded-lg m-3">
  <h1>Django Level Five Example</h1>
</div>

{% endblock %}

userAuth/basicApp/templates/basicApp/login.html
{% extends 'basicApp/base.html' %}
{% block body_block %}

<!-- This replaces jumbotron -->
<div class="bg-light p-5 rounded-lg m-3">
  <h1>Please Login</h1>
  <form action="{% url 'basicApp:user_login'%}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username"
          placeholder="Enter Username">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit" name="" value="Login">
  </form>
</div>

{% endblock %}

userAuth/basicApp/templates/basicApp/registration.html
{% extends "basicApp/base.html"%}
{% load static %}

{% block body_block %}

<!-- This replaces jumbotron -->
<div class="bg-light p-5 rounded-lg m-3">
  {% if registered %}
    <h1>Thank you for registering</h1>
  {% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the form:</h3>
  <form enctype = "multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Register">
  </form>
  {% endif %}
</div>

{% endblock %}